services:
  scrp-music:
    build:
      context: .
      args:
        VITE_DEFAULT_PROXY: ${VITE_DEFAULT_PROXY:-https://corsproxy.io/?}
        VITE_DEFAULT_API_KEYS: ${VITE_DEFAULT_API_KEYS:-}
    image: scrp-music
    container_name: scrp-music
    ports:
      - "3000:3000"
    environment:
      - RELAY_ENABLED=${RELAY_ENABLED:-true}
      - PORT=${PORT:-3000}
    restart: unless-stopped
